### ISSUE TITLE
Fix dependency on scss_lint

### ISSUE THREAD

**Issue by agross** [chrisrohr/guard-scss_lint#5]
The gemspec currently has `'scss_lint', '~> 0.43.0'`. That makes this gem depend on scss_lint >= 0.43.0 && < 0.44. The current version is scss_lint is 0.47, though.

Could you please updated the dependency to support more recent versions?

**Comment by chrisrohr** [comment]
@agross My apologies for the delayed response.  I have pushed out 0.1.5 with this update.
