### ISSUE TITLE
Changes to .scss-lint.yml are not picked up

### ISSUE THREAD

**Issue by aspiers** [chrisrohr/guard-scss_lint#7]
I tried the globbing technique suggested in #6 - it correctly reruns scss-lint on the files from the glob, but it does not take the changes to `.scss-lint.yml` into account; this only happened when I restarted Guard.  The plugin should automatically reload the configuration when it changes.

**Comment by chrisrohr** [comment]
@aspiers Thanks for reporting this.  I haven't touched this in a while, but I will check and see if I can add that option.

**Comment by chrisrohr** [comment]
@aspiers In looking into the code, I think if you add a second watch to your .scss-lint.yml file then it will watch for changes in that as well and rerun the guard. For instance change: 

```ruby
guard 'scss_lint' do
  watch(%r{^app/assets/stylesheets/.+.scss})
end
```
to 
```ruby
guard 'scss_lint' do
  watch(%r{^app/assets/stylesheets/.+.scss})
  watch(%r{^\.scss-lint\.yml})
end
```

If you are also asking that this be the default in the generate, I can do that, but it should be known that I can't detect a custom config file only auto add the default one.

**Comment by aspiers** [comment]
That's what I tried first and it didn't work but I can double check in case I was doing something stupid! Does it definitely work for you?

**Comment by aspiers** [comment]
OK upon further thought I think maybe there is confusion between two different problems here:

1. ensuring that changes to `.scss-lint.yml` trigger relinting `.scss` files
2. ensuring that changes to `.scss-lint.yml` are picked up before the relinting starts, so that they actually apply to the relinting

This GitHub issue mainly concerns problem 2, not problem 1.  Problem 1 is already solved using the glob technique.

It sounds like your suggestion of changing

    watch(%r{^\.scss-lint\.yml})

was intended to address problem 1 rather than problem 2, in which case it's not so relevant to this GitHub issue.  But even if not, when I try it, I get a weird error:

```
23:40:12 - ERROR - .scss-lint.yml:255:1 [E] Syntax: Syntax Error: Invalid CSS after "    enabled: false": expected "{", was ""                                
23:40:12 - INFO - Guard::ScssLint inspected 1 files, found 1 errors.
```

Thanks!

**Comment by chrisrohr** [comment]
Ah yes... sorry I see that now.  I will take a look and see how I can get it to reload the config on changes.  As for my solution to problem 1, it is failing because the .scss-lint.yml file isn't a css, sass, or scss file so that actually makes sense.

**Comment by chrisrohr** [comment]
I just pushed a patch to the gem that will reload the config.  Please try at your earliest convenience.

**Comment by aspiers** [comment]
Thanks, problem 2 is now fixed!  So I'll close this.

>As for my solution to problem 1, it is failing because the .scss-lint.yml file isn't a css, sass, or scss file so that actually makes sense.

Ah yeah, OK.  I'll file a separate issue about this.
